spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/shop"
    username: postgres
    password: 452389
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    name: "C:/Projects/online-shop/logs/logfile.log"
